# rule identifiers to exclude from running
disabled_rules:
 - block_based_kvo
 - class_delegate_protocol
 - closing_brace
 - closure_parameter_position
 - compiler_protocol_init
 - custom_rules
 - cyclomatic_complexity
 - discarded_notification_center_observer
 - discouraged_direct_init
 - dynamic_inline
 - empty_parentheses_with_trailing_closure
 - file_length
 - for_where
 - force_cast
 - force_try
 - function_body_length
 - function_parameter_count
 - generic_type_name
 - identifier_name
 - implicit_getter
 - is_disjoint
 - large_tuple
 - legacy_cggeometry_functions
 - legacy_constant
 - legacy_nsgeometry_functions
 - line_length
 - mark
 - multiple_closures_with_trailing_closure
 - nesting
 - no_fallthrough_only
 - notification_center_detachment
 - private_over_fileprivate
 - private_unit_test
 - protocol_property_accessors_order
 - redundant_set_access_control
 - return_arrow_whitespace
 - shorthand_operator
 - statement_position
 - superfluous_disable_command
 - todo
 - type_body_length
 - type_name
 - valid_ibinspectable
 - vertical_parameter_alignment
 - xctfail_message


# paths to ignore during linting. Takes precedence over `included`.
excluded:
 - Carthage
 - Pods
